- name: "Create SonarQube system group"
  group:
    name: "{{ sonar_group }}"
    state: present

- name: "Create SonarQube system user"
  user:
    name: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    createhome: no
    shell: "/sbin/nologin"
    comment: "SonarQube System user"
    state: present

- name: "Create SonarQube directories"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ sonar_user }}"
    group: "{{ sonar_group }}"
    mode: "u=rwx,g=rx,o="
  with_items:
    - "{{ sonar_install_directory }}"
    - "{{ sonar_logs_dir }}"
    - "{{ sonar_data_dir }}"
    - "{{ sonar_temp_dir }}"
    
- name: "fetch SonarQube binaries"
  fetch:
      source: "{{ sonar_downloaded_path }}"
      dest: "/tmp/{{ __sonar_archive }}"
  retries: 5
  delay: 10

- name: "Expand SonarQube binaries"
  unarchive:
      src: "/tmp/{{ __sonar_archive }}"
      dest: "{{ sonar_install_directory }}"
      owner: "{{ sonar_user }}"
      group: "{{ sonar_group }}"
      copy: no
- name: "Copy SonarQube systemd unit file into place "
  template:
    src: sonar.service.j2
    dest: /etc/systemd/system/sonar.service
    owner: root
    group: root
    mode: 0755
  register: systemd_service
  when: "ansible_service_mgr == 'systemd'"

- name: "Ensure SonarQube is running and set to start on boot."
  become: yes 
  become_user: "{{ sonar_user }}"
  service:
    name: sonar
    state: restart
    enabled: yes